PYTHON ?= python3
CXXFLAGS += -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color
CPPFLAGS += $(shell $(PYTHON) -m pybind11 --includes)
LIBNAME = helpers
LIBEXT = $(shell $(PYTHON) -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")

default: $(LIBNAME)$(LIBEXT)

%$(LIBEXT): %.cpp
	        $(CXX) $(CXXFLAGS) $(CPPFLAGS) $< -o $@
